version: "3"
services:
  default:
    build:
      context: .
    image: commnerd/workspace
    restart: always
    privileged: true
    ports:
      - 80:80
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/Workspace:/home/commnerd/Workspace
